language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1Golubeva_AllLab
  - make -j
  - ./StackTest/StackTest
  - ./Stack/Stack
notifications:
  email: false
