language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1Golubeva_AllLab
  - make -j
  - cd ./bin/
  - ./381706-1Golubeva_AllLab
notifications:
  email: false
