language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1Golubeva_AllLab
  - make -j
  - ./Queue/Queue
  - ./QueueTest/QueueTest
  - ./Stack/Stack
  - ./StackTest/StackTest
notifications:
  email: false
