language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1Golubeva_AllLab
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./ArrayListTests/ArrayListTests
  - ./ListTest/ListTest
  - ./MultiStackTest/MultiStackTest
  - ./PolishTest/PolishTest
  - ./PolynomialTest/PolynomialTest
  - ./QueueTest/QueueTest
  - ./StackListTest/StackListTest
  - ./TableTest/TableTest
notifications:
  email: false
